#!/usr/bin/env python

from tm_distribute import Distribution
from tm_distribute import TemplatePath
from tm_distribute import __version__

import argparse
import sys, os

def dist_type(value):
    value = int(value)
    if value > 0:
        return value
    raise ValueError()

def parse_args():
    default_templates_dir = TemplatePath
    default_output_dir = os.getcwd()
    parser = argparse.ArgumentParser()
    parser.add_argument('filename', help="XML trigger menu")
    parser.add_argument('-d', '--dist', type=dist_type, default=1, metavar='<n>', help="distribution number (1...n)")
    parser.add_argument('-o', dest='output', metavar='<dir>', default=default_output_dir, help="set distribution output directory")
    parser.add_argument('--templates', metavar='<dir>', default=default_templates_dir, help="set template input directory")
    parser.add_argument('--version', action='version', version='%(prog)s {}'.format(__version__))
    return parser.parse_args()

def main():
    args = parse_args()

    dist = Distribution(args.templates, args.filename)
    dist.write_impl(args.output, args.dist)

if __name__ == '__main__':
    main()
