/*
 * auto generated by {{ meta.proc.name }} v{{ meta.proc.version }}
 *
 * created: {{ meta.timestamp }}
 * menu name: {{ menu.name }}
 * menu UUID: {{ menu.uuid }}
 * dist UUID: {{ menu.dist_uuid }}
 * module: {{ module.id }}
 *
 */
{% block code %}
{% endblock code %}
/* eof */
